import Head from "next/head";
import { Main } from "@/component/Main";

export default function About() {
  return (
    <>
      <Head>
        <title>about page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main page="about" />
    </>
  );
}
