import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { HeadLine } from "@/component/HeadLine";
import { Links } from "@/component/Links";
import Images from "@/component/Images";

export default function Home() {
  return (
    <>
      <Head>
        <title>index page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HeadLine title="index" />

        <Images />
        <Links />
      </main>
    </>
  );
}
