import Head from "next/head";
import { Header } from "@/component/Header";
import styles from "@/styles/Home.module.css";
import Posts from "@/component/Posts";

const Home = () => {
  return (
    <>
      <Head>
        <title>index page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Posts />
    </>
  );
};
export default Home;
